### ISSUE TITLE
let's bump version to 1.0.0

### ISSUE THREAD

**Issue by revelt** [mateodelnorte/find-file-recursively-up#1]
hi Matt, guys,

First, thanks for coding this up. This library does work (I just tapped it), so let's bump the version to `1.0.0`. As you know, you get penalties when it's less than `1.0.0`, every release is considered _breaking_, even patch. Also, it will look more serious. I'm using BitHound and it does scan every dep.

What do you think?

**Comment by mateodelnorte** [comment]
Why would every release be considered breaking? Sounds like a bug in BitHound to me. Breaking changes are indicated by incrementing the major release number in semver.

**Comment by revelt** [comment]
I believe there's a bit of misunderstanding between us :)

Let me cite the official spec of [semver](http://semver.org/):

>4. Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.—http://semver.org/#spec-item-4

It has nothing to do with BitHound. I'm saying BitHound scans dependencies and measures the **perceived quality** of the libraries. If _your libraries_ were to have any "perceived deficiencies" whatsoever, no matter how small or trivial, _my libraries_ that consume them would have "perceived deficiencies". You might say "whoa, watch your language with "deficiencies"!", so let me elaborate.

Citing npms.io:

> Quality attributes are easy to calculate because they are self contained. These are the kind of attributes that a person looks first when looking at the package.
>
> * Has README? Has license? Has .gitignore and friends?
> * Is the version stable (> 1.x.x)? Is it deprecated?
> * Has tests? Whats their coverage %? Is build passing?
> * Has outdated dependencies? Do they have vulnerabilities?
> * Has custom website? Has badges?
> * Does the project have linters configured?
> —https://npms.io/about

Here's a kicker:

npms.io which **drives the search on npm** currently [scores](https://npms.io/search?q=find-file-recursively-up) this library at 37/100.

Not to mention corporate tools like [NodeSource](https://nodesource.com/products/certified-modules) which would definitely fail the certification at the moment because **it hasn't been tagged with the current release** (I just forked it and checked). Tagging requirement is a small dirty secret that many are using but nobody talks about. Personally I use [np](https://www.npmjs.com/package/np) to automate that. All my libraries are tagged.

Furthermore, this library is currently being served as `0.0.0`, so being strictly technical, it looks suspicious and might be considered by some as **breaking semver rules altogether**. Reading from the same semver spec: 

> The simplest thing to do is start your initial development release at 0.1.0 and then increment the minor version for each subsequent release.—http://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase

---

Do you see now that your library is not being presented at its best currently?

I'm happy to help with documentation, setup etc. It's a fine piece of code and it works. Just presentation needs some polishing.

What do you think?

**Comment by mateodelnorte** [comment]
Well, that was quite thorough. I appreciate it. ;) 

Sounds like it would be best positioned with all of your bullet points satisfied. Happy to start off by bumping to 1.0.0.

**Comment by mateodelnorte** [comment]
bumped, tagged, and published. thx. 
```
➜  find-file-recursively-up git:(master) git tag 1.0.0
➜  find-file-recursively-up git:(master) gp origin 1.0.0
Total 0 (delta 0), reused 0 (delta 0)
To github.com:mateodelnorte/find-file-recursively-up.git
 * [new tag]         1.0.0 -> 1.0.0
➜  find-file-recursively-up git:(master) npm publish
+ find-file-recursively-up@1.0.0
```

**Comment by revelt** [comment]
btw score increased to 52/100 instantly! https://npms.io/search?q=find-file-recursively-up
